export { default as CrafyHubLogo } from './logo.svg'
export { default as freelancers }  from './freelancers.svg'
export { default as payroll }  from './payroll.svg'
export {default as CrafyLogo} from './crafy_hub_logo.svg'
export {default as GLogo} from './G_logo.svg'
export {default as InstaLogo} from './InstaLogo.svg'